### ISSUE TITLE
Messy custom code

### ISSUE THREAD

**Issue by WarpPrime** [Goldorion/Array-Lists-MCreator#10]
The ArrayList block doesn't add a new line every time a block is added, making clean-up and debugging a lot harder than it needs to be. For example, many blocks chained together ends up with
`
stuff(Param);stuff(Param);stuff(Param);stuff(Param);stuff(Param);stuff(Param);stuff(Param);stuff(Param);stuff(Param);stuff(Param);
`
with no line spacing whatsoever. This makes debugging annoying as the console will end up overflowing off the screen.

**Comment by Goldorion** [comment]
Same issue as #4, moving it there for easier convenience when committing the fix
