### ISSUE TITLE
Some Blocks Don't Work??

### ISSUE THREAD

**Issue by FiveNights21611** [Goldorion/Array-Lists-MCreator#11]
So, Add Double to list is Broken. Not sure why.
But also, get item at index [number] of list (list) is broken.
I think lists are broken?
I can't do anything with the lists.

1.19.2 Forge Gen

I'm also using FileManager so I can make a config for stuff.

**Comment by FiveNights21611** [comment]
nothing's working. is there a core plugin I'm missing or something?

**Comment by FiveNights21611** [comment]
the specific error I'm getting comes from it trying to compile: error: incompatible types: Object cannot be converted to double

**Comment by Goldorion** [comment]
Same issue as #4, moving it there for easier convenience when committing the fix
