### ISSUE TITLE
Won't let me run my mod because it doesn't like my lists

### ISSUE THREAD

**Issue by FiveNights21611** [Goldorion/Array-Lists-MCreator#13]
I'm building a sort of infection system for blocks, and I'm using 2 Lists. One is for Infectable Blocks, one is Infected Blocks. I'm trying to get it to replace Infectable blocks with Infected blocks. However, it won't let me run it because it doesn't know what defaultBlockState is from the list. It makes using Replace Block and Set Block impossible, and I'm not even sure how to fix it with custom code. I tried, don't get me wrong. Removing defaultBlockState made it say it didn't know what was in the list. Adding it back and adding the libraries that another part of the mod used for defaultBlockState didn't work. I have no clue what to do now.

**Comment by Goldorion** [comment]
Same issue as #4, moving it there for easier convenience when committing the fix
