### ISSUE TITLE
String return from Array index flawed.

### ISSUE THREAD

**Issue by CreeperEntertain** [Goldorion/Array-Lists-MCreator#14]
Hey, short issue here.
I'm trying to use the array list for a goal list the player can create via a GUI element.
The issue I am experiencing is that it gives me compile errors if I want to get a return string that's a value at an array list index.
The blocks used: Return (string) > Get the value at index [0] of [Get (Global: GoalList)]

I'm using the Forge 1.19.2 generator.
The procedure mentioned is run from a GUI, and is used to return the string for a text object to display.

If more info is needed, I'll provide.
Thanks in advance!

**Comment by Goldorion** [comment]
Same issue as #4, moving it there for easier convenience when committing the fix
