### ISSUE TITLE
Get the value at index block causes can not be uses for specific things

### ISSUE THREAD

**Issue by Shadowdragon019** [Goldorion/Array-Lists-MCreator#4]
The ability to use Arrays for things like items, blocks, etc
I'm not sure if this isn't added or broken
Video! - https://www.youtube.com/watch?v=Yz1zskCj0OU

I'm like 99% this was talked about before but I can't remember what was said.

**Comment by Goldorion** [comment]
Could you provide your workspace or the console log (on pastebin), please?

**Comment by Shadowdragon019** [comment]
No, I can do BOTH! MWHAHAH!
Workspace - https://drive.google.com/drive/folders/1dlGlafVyp8j-Wd4_nGIHs5cdzNIEOJuv?usp=sharing
Console log, (I think this is the console log, as I just copied what MCreator showed me, if it's not correct please correct me!) - https://pastebin.com/UxcMHG6L

**Comment by Goldorion** [comment]
> 
> 
> No, I can do BOTH! MWHAHAH!
> Workspace - https://drive.google.com/drive/folders/1dlGlafVyp8j-Wd4_nGIHs5cdzNIEOJuv?usp=sharing
> Console log, (I think this is the console log, as I just copied what MCreator showed me, if it's not correct please correct me!) - https://pastebin.com/UxcMHG6L

I see what is the problem. I will see if I can do something to solve it, but to be honest, I think the only solution, for how it is currently, would be to have one getter for each special variable type (which is maybe not the best thing I think).

**Comment by Shadowdragon019** [comment]
I do not know code! Is there a way you could help me out? Like you just up'n'right telling me what to do or a random internet tutorial?

Also for the Only Solution maybe you could make code that detects "HEY IS THIS A X, OR A Y, etc?" and than does that. Of course for my purposes I'd be completely fine with the one for each type thing. Maybe you could implement that as a thing for till you get something better!

**Comment by Cure549** [comment]
Would this not be an optimal alternative to making special variable types?
![image](https://user-images.githubusercontent.com/22863739/124217742-e37e0a00-dac6-11eb-9ec7-f8e24cf9386e.png)

**Comment by Goldorion** [comment]
> Edit 2:
This compiled properly btw, and worked as intended.

It works properly because it's not the same generated code for the itemstack.

**Comment by Cure549** [comment]
Gotya.

**Comment by Cure549** [comment]
I'm not too familiar with how mcr generates code. But it seemed to generate the code that would work in that alternative in regards to the built-in itemstack var.

![image](https://user-images.githubusercontent.com/22863739/124218163-acf4bf00-dac7-11eb-91ea-113218f650d9.png)

![image](https://user-images.githubusercontent.com/22863739/124218175-b2eaa000-dac7-11eb-9173-a59d79b2e74b.png)

**Comment by Cure549** [comment]
I can definitely see the problem the more I mess around with it. Honestly, I think the only real way to go about it is what you mentioned earlier. Making different special array lists. Unfortunate really.

**Comment by Goldorion** [comment]
After almost 2 years, it's fixed... no I'm not late, you were too impatient! (Sorry)

**Comment by CreeperEntertain** [comment]
I believe the reason it was flawed is because, obviously, the arrayList is one of type object. And what I imagine went wrong is the code not getting generated as taking the value of an object, but trying to use the object by itself.

**Comment by Goldorion** [comment]
Yes, I can't do too complex things with variables, so this is only a just of objects (the most generic thing in Java). However, this can't work with everything, like templates we use for itemstack and blockstate
