### ISSUE TITLE
Compile error when trying to add values to array.

### ISSUE THREAD

**Issue by Cure549** [Goldorion/Array-Lists-MCreator#5]
Version: EAP 2021.2.26215

Console:
![image](https://user-images.githubusercontent.com/22863739/124213683-02789e00-dabf-11eb-9b85-d51b18168f65.png)

Procedure:
![image](https://user-images.githubusercontent.com/22863739/124213739-17edc800-dabf-11eb-8787-c3e92e846a71.png)

**Comment by Goldorion** [comment]
https://github.com/Goldorion/Array-Lists-MCreator/issues/4
