### ISSUE TITLE
ArrayLists throws error upon adding custom element

### ISSUE THREAD

**Issue by WarpPrime** [Goldorion/Array-Lists-MCreator#9]
The biggest issue I'm seeing with this plugin is that you cannot put custom ItemStacks into the ArrayList. Adding in something through `Blocks.COBBLESTONE` or `Items.COAL` goes without incident, but when trying to add a custom element like `CUSTOM:FooBar` throws 3 exceptions per block, saying that

```
[file path]: error: ')' expected 
StuffModVariables.ThisArrayList.add(CUSTOM:FooBar);
                                          ^ 
[file path]: error: not a statement 
StuffModVariables.ThisArrayList.add(CUSTOM:FooBar); 
                                           ^ 
[file path]: error: ';' expected 
StuffModVariables.ThisArrayList.add(CUSTOM:FooBar);
                                                 ^ 
```

I assume that this is because the illegal character `:` is included in the statement. Any workarounds?

I am running Mcreator 2022.3 latest build on a Win10 device. 

To reproduce the error, simply create a custom item, and add a procedure which adds the custom item to a global ArrayList.

**Comment by FiveNights21611** [comment]
I've had this issue too, trying to make a list of custom blocks to correspond to a list of normal blocks. Normal blocks work, but not Custom Blocks. I've been trying to use custom code to fix it myself for 1.18.2. It's been a pain.

**Comment by FiveNights21611** [comment]
I found a pretty simple fix to adding custom blocks.
Add this to the imports:
`import net.mcreator.[modid].init.[modname]ModBlocks;`
Then change the 'CUSTOM:FooBar' to
`[modname]ModBlocks.[block id in mcreator, all caps. basically, whatever the name of it is when you go to edit its properties]`

**Comment by Goldorion** [comment]
Same issue as #4, moving it there for easier convenience when committing the fix
